In [1]:
pip install mdtraj

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 2.1 MB 11.0 MB/s 
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
  Created wheel for mdtraj: filename=mdtraj-1.9.7-cp37-cp37m-linux_x86_64.whl size=5545871 sha256=d021f76a88b1e80fc33689dbff6682519bae6674f4acee14da64e83ca2fb82b4
  Stored in directory: /root/.cache/pip/wheels/6f/84/9d/6854e5264a4423209de26a6e4b34d13750289c72ba0439bbfd
Successfully built mdtraj


In [2]:
# importing necessary libraries

import mdtraj
import numpy

# import graphics library

%pylab inline
import matplotlib.pyplot as plt

Populating the interactive namespace from numpy and matplotlib


In [3]:
traj_1 = mdtraj.load('trj124.lh5')

In [28]:
angle_indices = [[1, 2, 3], [4, 5, 6]]
print(angle_indices)
ndim(angle_indices)
shape(angle_indices)

[[1, 2, 3], [4, 5, 6]]


(2, 3)

In [27]:
mdtraj.compute_angles(traj_1, angle_indices)
#Compute the bond angles between the supplied triplets of indices in each frame of a trajectory.


array([[2.0533895, 1.3304816],
       [2.0248704, 1.9637103],
       [2.0181618, 1.5278873],
       [2.0069187, 1.5359544],
       [2.053691 , 1.371304 ],
       [2.0425038, 1.2316005],
       [2.005143 , 1.3451483],
       [2.1530352, 1.5907977],
       [2.059033 , 1.3933454],
       [1.9355149, 1.3300186],
       [1.9562968, 1.4304246],
       [2.061586 , 1.533565 ],
       [1.9843533, 1.4312745],
       [2.0047655, 1.4058874],
       [2.0841548, 1.3230218],
       [2.0431082, 1.4339323],
       [1.9715128, 1.4823153],
       [2.06118  , 1.983667 ],
       [2.0748506, 1.6007698],
       [1.9860438, 1.4792163],
       [1.991925 , 1.5880489],
       [2.0123992, 1.4024898],
       [1.9445338, 1.5481058]], dtype=float32)

In [31]:
angle_indices = [[1, 2, 3,10], [4, 5, 6,11],[7,8,9,12]]
print(angle_indices)
ndim(angle_indices)
shape(angle_indices)

[[1, 2, 3, 10], [4, 5, 6, 11], [7, 8, 9, 12]]


(3, 4)

In [32]:

mdtraj.compute_dihedrals(traj_1, angle_indices, periodic=True, opt=True)

array([[ 0.32053164,  2.3204694 , -2.7160876 ],
       [-0.86970955,  2.4307466 , -3.0853724 ],
       [ 0.6090827 ,  2.0541089 , -2.9144325 ],
       [ 0.44353747,  2.2103605 , -2.875709  ],
       [ 0.6034984 ,  2.0652175 , -2.486884  ],
       [ 0.6204567 ,  2.2058733 , -2.775757  ],
       [ 0.47939903,  2.2248151 , -2.4505744 ],
       [-0.20632218,  2.4205213 , -2.936008  ],
       [ 0.38235223,  2.4335976 , -2.9803994 ],
       [ 0.5830074 ,  2.3601189 , -2.9289012 ],
       [ 0.6124295 ,  2.119749  , -3.001038  ],
       [ 0.66442823,  2.1044416 , -2.9686024 ],
       [ 0.30428904,  2.425295  , -3.0196636 ],
       [ 0.4986574 ,  2.2871869 , -2.971988  ],
       [ 0.36213323,  2.4514337 , -2.6459632 ],
       [ 0.4277894 ,  2.174562  , -2.84561   ],
       [ 0.39608374,  2.3544135 , -2.7850869 ],
       [-0.90806437,  2.5627832 , -2.8527014 ],
       [ 0.70217997,  2.02868   , -2.994889  ],
       [ 0.21274307,  2.3551958 , -2.8294146 ],
       [ 0.82346964,  1.9131912 , -2.625

In [33]:
mdtraj.compute_omega(traj_1, periodic=True, opt=True)

(array([[   1,    5,    7,    8],
        [   8,   19,   21,   22],
        [  22,   26,   28,   29],
        ...,
        [2145, 2151, 2153, 2154],
        [2154, 2159, 2161, 2162],
        [2162, 2167, 2169, 2170]]),
 array([[ 3.0077171, -3.1388087,  3.1019807, ..., -3.0758867,  3.0818431,
          2.9079444],
        [-3.0043206, -2.9843638,  3.121034 , ...,  3.136576 ,  3.0860536,
          2.9388962],
        [ 3.0697508,  3.0870662,  3.0348551, ...,  3.055461 ,  2.9754868,
          2.90953  ],
        ...,
        [-3.1042964, -3.089155 ,  2.8965743, ...,  3.0287824, -3.1366735,
          3.0621583],
        [ 3.0964882,  2.9118528,  3.0376947, ...,  3.1324682, -3.088469 ,
          2.860575 ],
        [ 3.094974 ,  3.032819 ,  3.041661 , ..., -2.9875526,  3.1024222,
          2.8868294]], dtype=float32))