In [1]:
pip install mdtraj

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 2.1 MB 14.6 MB/s 
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
  Created wheel for mdtraj: filename=mdtraj-1.9.7-cp37-cp37m-linux_x86_64.whl size=5545741 sha256=ceaf40e7350634655291d339c7fb29d91474d6e56ad25b5cf885a7b540787870
  Stored in directory: /root/.cache/pip/wheels/6f/84/9d/6854e5264a4423209de26a6e4b34d13750289c72ba0439bbfd
Successfully built mdtraj


In [2]:
# importing necessary libraries

import mdtraj
import numpy

# import graphics library

%pylab inline
import matplotlib.pyplot as plt

Populating the interactive namespace from numpy and matplotlib


In [4]:
traj_1 = mdtraj.load('trj155.lh5')

In [5]:
traj_2 = mdtraj.load('trj893.lh5')

In [6]:


combined_traj = traj_1 + traj_2

In [7]:
combined_traj

<mdtraj.Trajectory with 44 frames, 2175 atoms, 271 residues, without unitcells at 0x7f91c5bf0c10>

In [8]:
# computing the distance between pairs of atoms in residues 0 and 10 and residues 0 and 11.
combined_mdtraj_distance = mdtraj.compute_distances(combined_traj,atom_pairs = [[0, 10], [0, 11]])

array([[0.632807  , 0.71827596],
       [0.6639178 , 0.74317557],
       [0.64905256, 0.7381587 ],
       [0.6604948 , 0.7415309 ],
       [0.66517234, 0.75673574],
       [0.6209839 , 0.7142832 ],
       [0.6209228 , 0.7409336 ],
       [0.6574212 , 0.7407606 ],
       [0.6397754 , 0.7262987 ],
       [0.6442053 , 0.7152233 ],
       [0.65478325, 0.73081744],
       [0.6590214 , 0.7364382 ],
       [0.62870413, 0.7185244 ],
       [0.65528756, 0.73101693],
       [0.6501308 , 0.7277462 ],
       [0.63276184, 0.7090349 ],
       [0.65589404, 0.72692907],
       [0.6277938 , 0.6784399 ],
       [0.64469326, 0.7144349 ],
       [0.63914454, 0.72269005],
       [0.632807  , 0.71827596],
       [0.64028573, 0.7231183 ],
       [0.62793165, 0.720936  ],
       [0.631686  , 0.721863  ],
       [0.65997654, 0.7573571 ],
       [0.6662297 , 0.7425348 ],
       [0.6516485 , 0.75188416],
       [0.63702506, 0.717879  ],
       [0.6406652 , 0.757035  ],
       [0.6560877 , 0.74923044],
       [0.

In [9]:
# computing displacement vector between pairs of atom in each frame of a trajectory
combined_mdtraj_dislacement = mdtraj.compute_displacements(combined_traj,atom_pairs = [[0, 10], [0, 11]])

array([[[-0.4659996 , -0.08299994, -0.42000008],
        [-0.49199963, -0.19900012, -0.48399973]],

       [[-0.42700005, -0.10699987, -0.49699974],
        [-0.4380002 , -0.22899985, -0.5549998 ]],

       [[-0.388     , -0.15400004, -0.49700022],
        [-0.40700006, -0.27699995, -0.5500002 ]],

       [[-0.34700012,  0.        , -0.5620003 ],
        [-0.342     , -0.102     , -0.6500001 ]],

       [[-0.43400002,  0.03299999, -0.50300026],
        [-0.46600008, -0.06200004, -0.59299994]],

       [[-0.39000034,  0.13499999, -0.46399975],
        [-0.43599987,  0.05599999, -0.5629997 ]],

       [[-0.49300003,  0.16400003, -0.34000015],
        [-0.5890002 ,  0.13100004, -0.4300003 ]],

       [[-0.62700033,  0.04699993, -0.19200039],
        [-0.70200014, -0.05900002, -0.22900009]],

       [[-0.62999964,  0.05299997, -0.09800005],
        [-0.7129998 , -0.04999995, -0.12900019]],

       [[-0.63099957,  0.11399996,  0.0619998 ],
        [-0.70999956,  0.00699997,  0.08599997]],



In [10]:
combined_mdtraj_contacts = mdtraj.compute_contacts(combined_traj, [[0, 10], [0, 11]])

(array([[1.2307683, 1.3399497],
        [1.2906418, 1.4065   ],
        [1.3174975, 1.4625942],
        [1.4607713, 1.6110257],
        [1.3574219, 1.5248884],
        [1.2176117, 1.3335294],
        [1.256384 , 1.4121096],
        [1.1637079, 1.2596585],
        [1.1922382, 1.1753784],
        [1.183656 , 1.1356097],
        [1.2006508, 1.1510416],
        [1.1958349, 1.1475458],
        [1.1677848, 1.136356 ],
        [1.1894222, 1.1662264],
        [1.2805741, 1.2272917],
        [1.1965072, 1.2045116],
        [1.2185327, 1.2007304],
        [1.2240359, 1.2342529],
        [1.2197745, 1.14455  ],
        [1.1826742, 1.1201935],
        [1.2307683, 1.3399497],
        [1.3574804, 1.5129479],
        [1.4202898, 1.5766069],
        [1.3320917, 1.5268142],
        [1.329692 , 1.5055591],
        [1.2997252, 1.4211016],
        [1.2516323, 1.4157867],
        [1.2995807, 1.4561336],
        [1.248958 , 1.4431003],
        [1.317386 , 1.4725668],
        [1.2763406, 1.4137912],
        

In [11]:
combined_mdtraj_closest_heavy = mdtraj.compute_contacts(combined_traj, [[0, 10], [0, 11]], scheme='closest-heavy')

(array([[1.2307683, 1.3399497],
        [1.2906418, 1.4065   ],
        [1.3174975, 1.4625942],
        [1.4607713, 1.6110257],
        [1.3574219, 1.5248884],
        [1.2176117, 1.3335294],
        [1.256384 , 1.4121096],
        [1.1637079, 1.2596585],
        [1.1922382, 1.1753784],
        [1.183656 , 1.1356097],
        [1.2006508, 1.1510416],
        [1.1958349, 1.1475458],
        [1.1677848, 1.136356 ],
        [1.1894222, 1.1662264],
        [1.2805741, 1.2272917],
        [1.1965072, 1.2045116],
        [1.2185327, 1.2007304],
        [1.2240359, 1.2342529],
        [1.2197745, 1.14455  ],
        [1.1826742, 1.1201935],
        [1.2307683, 1.3399497],
        [1.3574804, 1.5129479],
        [1.4202898, 1.5766069],
        [1.3320917, 1.5268142],
        [1.329692 , 1.5055591],
        [1.2997252, 1.4211016],
        [1.2516323, 1.4157867],
        [1.2995807, 1.4561336],
        [1.248958 , 1.4431003],
        [1.317386 , 1.4725668],
        [1.2763406, 1.4137912],
        

In [12]:
combined_mdtraj_ca = mdtraj.compute_contacts(combined_traj, [[0, 10], [0, 11]], scheme='ca')

(array([[1.504164 , 1.6274971],
        [1.602532 , 1.7174624],
        [1.5908706, 1.7509563],
        [1.6972269, 1.8663514],
        [1.6362708, 1.8206079],
        [1.531768 , 1.670862 ],
        [1.5747298, 1.7448448],
        [1.4897983, 1.6576267],
        [1.4873772, 1.5984825],
        [1.4626013, 1.5870218],
        [1.4795947, 1.576993 ],
        [1.484074 , 1.5695866],
        [1.4567407, 1.5538188],
        [1.4336088, 1.56924  ],
        [1.5611252, 1.6674836],
        [1.4581758, 1.5916045],
        [1.5035809, 1.6040468],
        [1.5437944, 1.6506221],
        [1.4926025, 1.595821 ],
        [1.4660546, 1.5462906],
        [1.504164 , 1.6274971],
        [1.672619 , 1.8368467],
        [1.7056315, 1.868722 ],
        [1.6232023, 1.8463278],
        [1.649313 , 1.8203498],
        [1.586244 , 1.7318538],
        [1.5413823, 1.7391869],
        [1.5863495, 1.7662101],
        [1.5987798, 1.7794406],
        [1.5998473, 1.7784408],
        [1.5610403, 1.7203608],
        

In [13]:
combined_mdtraj_sidechain = mdtraj.compute_contacts(combined_traj, [[0, 10], [0, 11]], scheme='sidechain')

(array([[1.4192678, 1.5296398],
        [1.597159 , 1.6321203],
        [1.6079955, 1.7570567],
        [1.7248399, 1.9361   ],
        [1.6690221, 1.8606441],
        [1.5166335, 1.5767624],
        [1.4797144, 1.6402817],
        [1.3826559, 1.4131746],
        [1.3877935, 1.2803763],
        [1.3800933, 1.2560453],
        [1.4305329, 1.2493732],
        [1.3981823, 1.2391045],
        [1.3420272, 1.1801207],
        [1.3294342, 1.2249874],
        [1.4712073, 1.3324525],
        [1.3993098, 1.3230573],
        [1.4417553, 1.3096063],
        [1.509111 , 1.3890158],
        [1.4812744, 1.3006868],
        [1.4632   , 1.2579957],
        [1.4192678, 1.5296398],
        [1.6192424, 1.7923412],
        [1.7084123, 1.898042 ],
        [1.6116815, 1.9069694],
        [1.6488211, 1.8520254],
        [1.5848861, 1.7019831],
        [1.4797821, 1.7092716],
        [1.5816783, 1.7908407],
        [1.524764 , 1.7508553],
        [1.6196547, 1.773848 ],
        [1.5292691, 1.7032692],
        

In [16]:
combined_mdtraj_sidechain_heavy = mdtraj.compute_contacts(combined_traj, [[0, 10], [0, 11]], scheme='sidechain-heavy')

/usr/local/lib/python3.7/dist-packages/mdtraj/geometry/contact.py:199: UserWarning: selected topology includes at least one glycine residue, which has no heavy atoms in its sidechain. The distances involving glycine residues will be computed using the sidechain hydrogen instead.
  warnings.warn('selected topology includes at least one glycine residue, which has no heavy atoms in its sidechain. The distances involving glycine residues '
